# Data processing

## Contents <a id=ov>
1. [Saving and Loading Data](#save)
2. [Numpy](#np)
3. [Saving and loading data into Pandas dataframe](#save_pandas)
4. [Investigate your Pandas dataframe](#Investigate)
5. [Pandas Series Object ](#series)
6. [Indexing and filtering](#filter)
7. [Plotting](#plt)
8. [Statsmodels](#sm)




## Saving and Loading Data <a id=save>
### Pickle
You can save or load every Python object via pickle:

In [1]:
import pickle

football_players={'Neymar':['PSG',29,100],
                  'Haaland':['BVB',21,150],
                  'Lukaku':['Chelsea',28,100],
                  'Messi':['PSG',34,80],
                  'Goretzka':['Bayern',26,70],
                  'Salah':['Liverpool',29,100],
                  'Kane':['Tottenham',28,120],
                  'Folden':['ManU',21,80]}
#saving
pickle.dump(football_players,open('football_players.p','wb'))
print('football_players.p','saved!')

football_players.p saved!


In [5]:
#load
football_players=pickle.load(open('football_players.p','rb'))
print(football_players)

{'Neymar': ['PSG', 29, 100], 'Haaland': ['BVB', 21, 150], 'Lukaku': ['Chelsea', 28, 100], 'Messi': ['PSG', 34, 80], 'Goretzka': ['Bayern', 26, 70], 'Salah': ['Liverpool', 29, 100], 'Kane': ['Tottenham', 28, 120], 'Folden': ['ManU', 21, 80]}


### Text files

Load Text files with ``open()``!

In [8]:
reader=open('tu_dortmund.txt','r')
reader=open('tu_dortmund.txt',encoding='utf-8')

list_of_rows=[row.replace('\n','') for row in reader]
#print(list_of_rows)
#list_of_rows=[row.replace('\n','') for row in open('tu_dortmund.txt','r')]

for i in range(0,10):
    print(list_of_rows[i])

Technische Universität Dortmund
(Weitergeleitet von TU Dortmund)
Zur Navigation springenZur Suche springen
Technische Universität Dortmund

Gründung	16. Dezember 1968
Trägerschaft	staatlich
Ort	Dortmund
Bundesland	 Nordrhein-Westfalen
Land	 Deutschland


Write text files with ``write`` or ``print()``.

In [9]:
with open('output_file.txt','w') as out_file:
    for i in range(0,10):
        out_file.write(str(list_of_rows[i])+'\n')
    print('output_file.txt','saved!')
    


output_file.txt saved!


In [10]:
with open('output_file2.txt','w') as out_file:
    for i in range(0,10):
        print(i,list_of_rows[i],'end_of_line',sep='|',end='\n',file=out_file)
    print('output_file_2.txt','saved!')

output_file_2.txt saved!


In [11]:
with open('output_file2.txt','a') as out_file:
    for i in range(15,100):
        print(i,list_of_rows[i],'end_of_line',sep='|',end='\n',file=out_file)
    print('output_file_2.text','appended!')


output_file_2.text appended!


### JSON files
The best way to save datasets with consist of dictionaries, list, strings and numericals  is ***JSON***, because it is readable for humans and other programming languages:


In [12]:
import json
#save
with open('football_players.json','w') as file:
    json.dump(football_players,file)


#load
with open('football_players.json') as json_object:
    python_object=json.load(json_object)

print(python_object)

{'Neymar': ['PSG', 29, 100], 'Haaland': ['BVB', 21, 150], 'Lukaku': ['Chelsea', 28, 100], 'Messi': ['PSG', 34, 80], 'Goretzka': ['Bayern', 26, 70], 'Salah': ['Liverpool', 29, 100], 'Kane': ['Tottenham', 28, 120], 'Folden': ['ManU', 21, 80]}


### XML files
XML files can be parse with Beautifulsoup. For large files, however, treating the file als text using ``open()`` and searching for keys with string methods can be more efficient.

## Numpy <a id=np>
[Back to Content Overview](#ov)

Numpy is the Python library for vector/matrix operations. Most of the import packages in data science and machine learning.

In [26]:
import numpy as np

### Basics
You can define a vector/matrix in the following way:

In [16]:
test_vector=np.array([[1,4,5],[7,3,6]])
print(type(test_vector))
print(test_vector)

<class 'numpy.ndarray'>
[[1 4 5]
 [7 3 6]]


In [17]:
# Get the dimensions of the array:
print(np.shape(test_vector))

(2, 3)


In [18]:
# Transpose the array:
print(test_vector.transpose())
print(test_vector.T)

[[1 7]
 [4 3]
 [5 6]]
[[1 7]
 [4 3]
 [5 6]]


In [19]:
# Change the shape of the array
print(np.array(range(0,10)).reshape((2,5)))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [20]:
[10,2,3,46]+1

TypeError: can only concatenate list (not "int") to list

In [21]:
np.array([10,2,3,46])+1

array([11,  3,  4, 47])

#### Special Arrays:

In [22]:
# Array with zeros:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# Array with ones:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# Array with range of numbers:
print(np.arange(10))
print(np.array(range(10))) # Similar

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [27]:
# Array with equally distributed numbers in a interval
print(np.linspace(0, 1, 60))

[0.         0.01694915 0.03389831 0.05084746 0.06779661 0.08474576
 0.10169492 0.11864407 0.13559322 0.15254237 0.16949153 0.18644068
 0.20338983 0.22033898 0.23728814 0.25423729 0.27118644 0.28813559
 0.30508475 0.3220339  0.33898305 0.3559322  0.37288136 0.38983051
 0.40677966 0.42372881 0.44067797 0.45762712 0.47457627 0.49152542
 0.50847458 0.52542373 0.54237288 0.55932203 0.57627119 0.59322034
 0.61016949 0.62711864 0.6440678  0.66101695 0.6779661  0.69491525
 0.71186441 0.72881356 0.74576271 0.76271186 0.77966102 0.79661017
 0.81355932 0.83050847 0.84745763 0.86440678 0.88135593 0.89830508
 0.91525424 0.93220339 0.94915254 0.96610169 0.98305085 1.        ]


#### Random:

In [28]:
# Array with random numbers between 0 and 1:
print(np.random.random(size=5))

[0.78572005 0.50113752 0.69753352 0.5584552  0.61020457]


In [29]:
# Array with random integers
print(np.random.randint(0,10,size=200))

[2 0 2 0 6 5 7 6 8 2 2 9 0 3 2 7 2 8 7 2 0 2 2 3 1 0 7 5 4 6 4 1 0 0 6 4 1
 7 0 4 3 6 3 0 4 8 9 9 0 8 9 2 2 1 6 0 6 0 7 7 2 2 2 8 8 3 8 2 1 6 1 1 0 7
 8 6 9 3 2 1 8 1 1 7 5 1 9 2 8 4 8 6 4 7 8 2 1 7 2 9 2 6 3 0 4 5 0 3 3 6 5
 0 3 1 4 8 3 1 8 9 4 4 0 1 4 4 5 4 9 0 0 5 8 6 8 0 7 0 4 1 8 7 8 0 0 1 5 9
 8 0 3 7 2 6 1 5 8 5 9 3 4 6 7 3 4 7 7 8 9 8 7 2 0 7 1 6 8 2 7 1 0 8 0 1 6
 8 7 0 2 5 4 3 3 5 7 9 1 7 0 6]


In [30]:
# Array with normal dist. random numbers:
print(np.random.normal(loc=0.0, scale=1.0, size=6))

[ 0.12934193 -0.07115213  0.39398202  0.65643697 -0.03523095  0.02223912]


#### Indexing:

In [31]:
test_vector=np.array([[1,4,5,6],[7,3,6,3],[3,3,1,9]])
print(test_vector)

[[1 4 5 6]
 [7 3 6 3]
 [3 3 1 9]]


In [32]:
# Print frist row
print(test_vector[0,:])

[1 4 5 6]


In [33]:
# Print last column
print(test_vector[:,-1])

[6 3 9]


<span style="color:blue"><b>Task:</b></span> Print the 2x2 matrix in the lower, right corner.

In [37]:
test_vector[1:,2:]
test_vector[-2:,-2:]

array([[6, 3],
       [1, 9]])

<span style="color:blue"><b>Task:</b></span> Create a  4x4 identity matrix!

In [38]:
# Use a for loop!
mat=np.zeros((4,4))
for i in range(4):
    for j in range(4):
        if i==j:
            mat[i,j]=1
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
# Use a for loop!
mat=np.zeros((4,4))
for i in range(4):
    mat[i,i]=1           
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [40]:
# Use a the diagonal method!
mat=np.matrix(4)
print(mat)

[[4]]


In [47]:
mat=np.diag([1,1,1,1])
mat=np.diag([1.0]*4)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [46]:
# Use a the method numpy method provides for you!
mat=np.identity(4)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [49]:
mat=np.eye(4)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


You can also index arrays with booleans:

In [50]:
print(test_vector)
print(test_vector[test_vector>3])

[[1 4 5 6]
 [7 3 6 3]
 [3 3 1 9]]
[4 5 6 7 6 9]


In [51]:
[test_vector>3]

[array([[False,  True,  True,  True],
        [ True, False,  True, False],
        [False, False, False,  True]])]

#### Stacking
You can also stack vector or matrices horizontally or vertically :

In [52]:
test_vector=np.array([[1,4,5],[7,3,6]])
print(test_vector)

[[1 4 5]
 [7 3 6]]


In [53]:
#Stack horizontally:
print(np.hstack((test_vector,test_vector)))

[[1 4 5 1 4 5]
 [7 3 6 7 3 6]]


In [54]:
#Stack vertically:
print(np.vstack((test_vector,test_vector)))

[[1 4 5]
 [7 3 6]
 [1 4 5]
 [7 3 6]]


#### Sorting:

In [55]:
sort_vector=np.random.randint(0,10,size=20)
print(sort_vector)

[8 6 8 3 1 5 7 1 1 8 0 5 3 7 9 5 3 3 0 9]


In [56]:
# Sort vector
print(np.sort(sort_vector))

[0 0 1 1 1 3 3 3 3 5 5 5 6 7 7 8 8 8 9 9]


In [57]:
# Gives back the new indices of the elements if the vector would be sorted:
print(np.argsort(sort_vector))

[18 10  4  7  8 17  3 12 16  5 11 15  1  6 13  0  9  2 14 19]


In [58]:
print(sort_vector[np.argsort(sort_vector)])

[0 0 1 1 1 3 3 3 3 5 5 5 6 7 7 8 8 8 9 9]


In [59]:
# You can use if to sort an vector with order of an other vector:
sort_vector_2=np.random.randint(0,10,size=20)
print(sort_vector_2)
print(sort_vector_2[np.argsort(sort_vector)])

[6 4 8 1 5 4 2 0 8 7 6 6 8 3 1 3 3 1 0 5]
[0 6 5 0 8 1 1 8 3 4 6 3 4 2 3 6 7 8 1 5]


In [72]:
names=np.array(['Person1','Person2','Person3'])
age=np.array([14,99,7])
names[np.argsort(age)]

array(['Person3', 'Person1', 'Person2'], dtype='<U7')

In [66]:
#There are also function to find the minimum or maximum value of vector:
print(np.max(sort_vector))
print(np.min(sort_vector))
print(np.argmax(sort_vector))
print(np.argmin(sort_vector))

9
0
14
10


#### Mathematical functions:

There are all standard (and not so standard)  [mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html) in numpy:

In [67]:
test_vector=np.array([[1,4,5,6],[7,3,6,3],[3,3,1,9]])
print(test_vector)

[[1 4 5 6]
 [7 3 6 3]
 [3 3 1 9]]


In [68]:
#Total sum
print(np.sum(test_vector))

51


In [69]:
#Sum for every column
print(np.sum(test_vector,axis=0))

[11 10 12 18]


In [70]:
#Sum for every row
print(np.sum(test_vector,axis=1))

[16 19 16]


<span style="color:blue"><b>Task:</b></span> Calculate the mean for the first two rows steperately. (2 Versions)

In [76]:
[16/4,19/4]
print(np.sum(test_vector[0,:])/len(test_vector[0,:]))
print(np.sum(test_vector[1,:])/len(test_vector[1,:]))

4.0
4.75


In [77]:
print(np.mean(test_vector[0]))
print(np.mean(test_vector[1]))

4.0
4.75


In [79]:
print(np.mean(test_vector[:2],axis=1)) # Faster

[4.   4.75]


In [80]:
print(np.mean(test_vector,axis=1)[:2])

[4.   4.75]


In [81]:
# You also apply the stand math operators on numpy arrays:
print(test_vector*2)
print(test_vector%3)

[[ 2  8 10 12]
 [14  6 12  6]
 [ 6  6  2 18]]
[[1 1 2 0]
 [1 0 0 0]
 [0 0 1 0]]


In [82]:
print(np.var(test_vector,axis=0)**0.5)
print(np.std(test_vector,axis=0))

[2.49443826 0.47140452 2.1602469  2.44948974]
[2.49443826 0.47140452 2.1602469  2.44948974]


In [83]:
print(np.sin(test_vector))
print(np.cos(test_vector))
print(np.tan(test_vector))

[[ 0.84147098 -0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.14112001 -0.2794155   0.14112001]
 [ 0.14112001  0.14112001  0.84147098  0.41211849]]
[[ 0.54030231 -0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.9899925   0.96017029 -0.9899925 ]
 [-0.9899925  -0.9899925   0.54030231 -0.91113026]]
[[ 1.55740772  1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -0.14254654 -0.29100619 -0.14254654]
 [-0.14254654 -0.14254654  1.55740772 -0.45231566]]


<span style="color:blue"><b>Task:</b></span> Rebuild this numpy.sin function with a for loop.

<span style="color:blue"><b>Task:</b></span> Calculate the sum of squares for every column.

In [85]:
test_vector**2

array([[ 1, 16, 25, 36],
       [49,  9, 36,  9],
       [ 9,  9,  1, 81]])

In [84]:
np.sum(test_vector**2,axis=0)

array([ 59,  34,  62, 126])

<span style="color:blue"><b>Task:</b></span> Standardise the test_vector.

In [86]:
#(vector -mean) / std
(test_vector-np.mean(test_vector))/np.std(test_vector)


array([[-1.40455069, -0.10804236,  0.32412708,  0.75629653],
       [ 1.18846597, -0.5402118 ,  0.75629653, -0.5402118 ],
       [-0.5402118 , -0.5402118 , -1.40455069,  2.05280486]])

#### Other functions

In [87]:
test_vector=np.array([[1,4,5,6],[7,3,6,3],[3,3,1,9]])
test_vector_2=np.array([[4,2,9,1],[7,4,6,3],[2,4,1,9]])

In [88]:
# Use where to apply condition on vectors.
print(np.where(test_vector>=test_vector_2,test_vector,np.nan))

[[nan  4. nan  6.]
 [ 7. nan  6.  3.]
 [ 3. nan  1.  9.]]


In [89]:
# Use unique to delete duplicates and retrun the counts.
print(np.unique(test_vector,return_counts=True))

(array([1, 3, 4, 5, 6, 7, 9]), array([2, 4, 1, 1, 2, 1, 1], dtype=int64))


In [90]:
unique_vector,counts=np.unique(test_vector,return_counts=True)
print(unique_vector)
print(counts)

[1 3 4 5 6 7 9]
[2 4 1 1 2 1 1]


<span style="color:blue"><b>Task:</b></span> Sort the unique values with its counts in descending order.

In [91]:
count_sort_index=np.argsort(-counts)
unique_vector[count_sort_index]

array([3, 1, 6, 4, 5, 7, 9])

In [92]:
count_sort_index=np.argsort(counts)
unique_vector[count_sort_index][::-1]

array([3, 6, 1, 9, 7, 5, 4])

## Saving and loading data into Pandas dataframe <a id=savepandas>
[Back to Content Overview](#ov)

In [2]:
import pandas as pd

C:\Users\myfix\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


The mean object of the pandas module is the dataframe. A datatable with named rows and columns:

In [94]:
#Import data from a matrix
column_names=['column_'+str(i) for i in range(0,4)]
print(column_names)
df=pd.DataFrame(data=test_vector,columns=column_names,index=None)

['column_0', 'column_1', 'column_2', 'column_3']


In [95]:
df

column_0  column_1  column_2  column_3
0         1         4         5         6
1         7         3         6         3
2         3         3         1         9

In [96]:
print(df)
print(df.index,list(df.index))
print(df.columns)

   column_0  column_1  column_2  column_3
0         1         4         5         6
1         7         3         6         3
2         3         3         1         9
RangeIndex(start=0, stop=3, step=1) [0, 1, 2]
Index(['column_0', 'column_1', 'column_2', 'column_3'], dtype='object')


In [99]:
#You can change the indices and columns via:
df.index=[1,2,3]
df.columns=['one','two','three','four']

print(df)

   one  two  three  four
1    1    4      5     6
2    7    3      6     3
3    3    3      1     9


In [100]:
#You access columns similar to dict value:
print(df['one'])

print(list(df['one']))

1    1
2    7
3    3
Name: one, dtype: int32
[1, 7, 3]


In [101]:
for col in df.columns:
    print(df[col])

1    1
2    7
3    3
Name: one, dtype: int32
1    4
2    3
3    3
Name: two, dtype: int32
1    5
2    6
3    1
Name: three, dtype: int32
1    6
2    3
3    9
Name: four, dtype: int32


### Importing and saving data

In [102]:
#Import data from a nested_list
df=pd.DataFrame(data=[[1,4,5,6],[7,3,6,3],[3,3,1,9]],columns=None,index=None)
print(df)


   0  1  2  3
0  1  4  5  6
1  7  3  6  3
2  3  3  1  9


In [103]:
#Import data from a dict
data_dict={'col1':[1,4,5,6],'col2':[7,3,6,3],'col3':[3,3,1,9]}
df=pd.DataFrame(data=data_dict)
print(df)

   col1  col2  col3
0     1     7     3
1     4     3     3
2     5     6     1
3     6     3     9


In [104]:
#Import data from a dict
data_dict={'col1':{'ind1':23,'ind1':1,'ind3':'string'},'col2':{'ind1':89,'ind3':'string'},'col3':{'ind3':'hello'}}
data_dict['col1']['ind1']=688
df=pd.DataFrame(data=data_dict)
print(df)

        col1    col2   col3
ind1     688      89    NaN
ind3  string  string  hello


In [105]:
#Save as csv
df.to_csv('test_df.csv')

In [114]:
import sys
!{sys.executable} -m pip install openpyxl==3.1.0
#Save as excel
df.to_excel('test_df.xlsx')

## Investigate your Pandas dataframe <a id=Investigate>
[Back to Content Overview](#ov)

In [3]:
#Import data from a excel_file
df=pd.read_excel('top_500_football_players.xlsx',sheet_name='final')
print(df)

       #          Player            Position  Age Market value  Matches  \
0      1   Kylian Mbappé      Centre-Forward   22    €160.00m        11   
1      2  Erling Haaland      Centre-Forward   21    €150.00m         8   
2      3      Harry Kane      Centre-Forward   28    €120.00m        10   
3      4   Jack Grealish         Left Winger   26    €100.00m        10   
4      5   Mohamed Salah        Right Winger   29    €100.00m         9   
..   ...             ...                 ...  ...          ...      ...   
495  496      Tom Davies    Central Midfield   23     €18.00m         5   
496  497   Hans Hateboer          Right-Back   27     €18.00m         0   
497  498      David Raya          Goalkeeper   26     €18.00m         7   
498  499    Gregor Kobel          Goalkeeper   23     €18.00m        12   
499  500  Wilmar Barrios  Defensive Midfield   27     €18.00m        10   

     Goals  Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
0        4          0 

In [4]:
#Show all columns names
print(df.columns)

Index(['#', 'Player', 'Position', 'Age', 'Market value', 'Matches', 'Goals',
       'Own goals', 'Assists', 'Yellow cards', 'Yellow red cards', 'Red cards',
       'Substitutions on', 'Substitutions off'],
      dtype='object')


In [5]:
#Show all row names
print(df.index)

RangeIndex(start=0, stop=500, step=1)


In [6]:
#Show the ten most valueable players
print(df.head(10))

    #           Player            Position  Age Market value  Matches  Goals  \
0   1    Kylian Mbappé      Centre-Forward   22    €160.00m        11      4   
1   2   Erling Haaland      Centre-Forward   21    €150.00m         8     11   
2   3       Harry Kane      Centre-Forward   28    €120.00m        10      6   
3   4    Jack Grealish         Left Winger   26    €100.00m        10      2   
4   5    Mohamed Salah        Right Winger   29    €100.00m         9      9   
5   6    Romelu Lukaku      Centre-Forward   28    €100.00m         9      4   
6   7  Kevin De Bruyne  Attacking Midfield   30    €100.00m         7      2   
7   8           Neymar         Left Winger   29    €100.00m         7      1   
8   9     Jadon Sancho         Left Winger   21     €90.00m         9      0   
9  10  Frenkie de Jong    Central Midfield   24     €90.00m         8      0   

   Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
0          0        5             2                

In [7]:
#Show Mr. Irrelevant
print(df.tail(1))

       #          Player            Position  Age Market value  Matches  \
499  500  Wilmar Barrios  Defensive Midfield   27     €18.00m        10   

     Goals  Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
499      0          0        0             0                 0          0   

     Substitutions on  Substitutions off  
499                 0                  2  


In [8]:
#Show the data types of columns
print(df.dtypes)

#                     int64
Player               object
Position             object
Age                   int64
Market value         object
Matches               int64
Goals                 int64
Own goals             int64
Assists               int64
Yellow cards          int64
Yellow red cards      int64
Red cards             int64
Substitutions on      int64
Substitutions off     int64
dtype: object


In [9]:
#Count the data types of columns
print(df.dtypes.value_counts())

int64     11
object     3
Name: count, dtype: int64


In [10]:
#Count the age of the players
print(df['Age'].value_counts())

Age
24    73
25    55
23    51
26    48
28    45
27    44
22    41
21    33
29    30
30    26
20    19
19     9
18     9
31     8
33     3
32     3
36     1
34     1
16     1
Name: count, dtype: int64


In [12]:
#Show all players with age 36
print(df[df['Age']==33]['Player'])

64     Robert Lewandowski
336         Karim Benzema
464        Ángel Di María
Name: Player, dtype: object


In [13]:
#Show the most important informations of the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   #                  500 non-null    int64 
 1   Player             500 non-null    object
 2   Position           500 non-null    object
 3   Age                500 non-null    int64 
 4   Market value       500 non-null    object
 5   Matches            500 non-null    int64 
 6   Goals              500 non-null    int64 
 7   Own goals          500 non-null    int64 
 8   Assists            500 non-null    int64 
 9   Yellow cards       500 non-null    int64 
 10  Yellow red cards   500 non-null    int64 
 11  Red cards          500 non-null    int64 
 12  Substitutions on   500 non-null    int64 
 13  Substitutions off  500 non-null    int64 
dtypes: int64(11), object(3)
memory usage: 54.8+ KB


In [14]:
#Show the most important statistics of the dataframe
df.describe()

#         Age    Matches       Goals   Own goals     Assists  \
count  500.000000  500.000000  500.00000  500.000000  500.000000  500.000000   
mean   250.500000   24.966000    7.62600    1.316000    0.012000    0.910000   
std    144.481833    3.191428    3.12885    1.976856    0.108994    1.274814   
min      1.000000   16.000000    0.00000    0.000000    0.000000    0.000000   
25%    125.750000   23.000000    6.00000    0.000000    0.000000    0.000000   
50%    250.500000   25.000000    8.00000    1.000000    0.000000    0.000000   
75%    375.250000   27.000000   10.00000    2.000000    0.000000    1.000000   
max    500.000000   36.000000   17.00000   13.000000    1.000000    7.000000   

       Yellow cards  Yellow red cards  Red cards  Substitutions on  \
count    500.000000        500.000000  500.00000        500.000000   
mean       0.966000          0.026000    0.02200          1.426000   
std        1.052168          0.159295    0.14683          1.740858   
min        0.000000          0.000000    0.00000          0.000000   
25%        0.000000          0.000000    0.00000          0.000000   
50%        1.000000          0.000000    0.00000          1.000000   
75%        1.000000          0.000000    0.00000          2.000000   
max        6.000000          1.000000    1.00000          9.000000   

       Substitutions off  
count         500.000000  
mean            2.352000  
std             2.286165  
min             0.000000  
25%             0.000000  
50%             2.000000  
75%             4.000000  
max            15.000000

<span style="color:blue"><b>Task:</b></span> Replicate df.disscribe! Hint: Use numpy to calcalate the statistical measures. 

In [18]:
df_discribe=pd.DataFrame()

# Iterate over the columns
for col in df.columns[df.dtypes=='int64']:
    c=df[col]
    df_discribe[col]=[c.count(),
                      c.mean(),
                      c.std(),
                      c.min(),
                      c.quantile(0.25),
                      c.quantile(0.5),
                      c.quantile(0.75),
                      c.max()]

df_discribe.index=['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']
df_discribe

#         Age    Matches       Goals   Own goals     Assists  \
count  500.000000  500.000000  500.00000  500.000000  500.000000  500.000000   
mean   250.500000   24.966000    7.62600    1.316000    0.012000    0.910000   
std    144.481833    3.191428    3.12885    1.976856    0.108994    1.274814   
min      1.000000   16.000000    0.00000    0.000000    0.000000    0.000000   
25%    125.750000   23.000000    6.00000    0.000000    0.000000    0.000000   
50%    250.500000   25.000000    8.00000    1.000000    0.000000    0.000000   
75%    375.250000   27.000000   10.00000    2.000000    0.000000    1.000000   
max    500.000000   36.000000   17.00000   13.000000    1.000000    7.000000   

       Yellow cards  Yellow red cards  Red cards  Substitutions on  \
count    500.000000        500.000000  500.00000        500.000000   
mean       0.966000          0.026000    0.02200          1.426000   
std        1.052168          0.159295    0.14683          1.740858   
min        0.000000          0.000000    0.00000          0.000000   
25%        0.000000          0.000000    0.00000          0.000000   
50%        1.000000          0.000000    0.00000          1.000000   
75%        1.000000          0.000000    0.00000          2.000000   
max        6.000000          1.000000    1.00000          9.000000   

       Substitutions off  
count         500.000000  
mean            2.352000  
std             2.286165  
min             0.000000  
25%             0.000000  
50%             2.000000  
75%             4.000000  
max            15.000000

## Pandas Series Object <a id=series>
[Back to Content Overview](#ov)

Every column of a dataframe is a Pandas Series Object.

In [19]:
print(df['Age'])

0      22
1      21
2      28
3      26
4      29
       ..
495    23
496    27
497    26
498    23
499    27
Name: Age, Length: 500, dtype: int64


In [21]:
print(type(df['Age']))

<class 'pandas.core.series.Series'>


You can also define them manually:

In [22]:
test_series = pd.Series(range(3,16))
print(test_series)

0      3
1      4
2      5
3      6
4      7
5      8
6      9
7     10
8     11
9     12
10    13
11    14
12    15
dtype: int64


In [23]:
# You also give them a name:
test_series.name = 'Magic Series'
print(test_series)

0      3
1      4
2      5
3      6
4      7
5      8
6      9
7     10
8     11
9     12
10    13
11    14
12    15
Name: Magic Series, dtype: int64


Series have some specifc functions ...

In [24]:
print(test_series.sum())
print(test_series.mean())
print(test_series.value_counts())

117
9.0
Magic Series
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: count, dtype: int64


... but you can also tread them as numpy vectors and apply every numpy function on them:

In [27]:
print(np.sum(test_series))
print(np.sum(test_series[test_series**2>20]))

117
110


In [28]:
# Add the new column to the dataframe
df['Scorer Points']=df['Goals']+df['Assists']
print(df.head(10))

    #           Player            Position  Age Market value  Matches  Goals  \
0   1    Kylian Mbappé      Centre-Forward   22    €160.00m        11      4   
1   2   Erling Haaland      Centre-Forward   21    €150.00m         8     11   
2   3       Harry Kane      Centre-Forward   28    €120.00m        10      6   
3   4    Jack Grealish         Left Winger   26    €100.00m        10      2   
4   5    Mohamed Salah        Right Winger   29    €100.00m         9      9   
5   6    Romelu Lukaku      Centre-Forward   28    €100.00m         9      4   
6   7  Kevin De Bruyne  Attacking Midfield   30    €100.00m         7      2   
7   8           Neymar         Left Winger   29    €100.00m         7      1   
8   9     Jadon Sancho         Left Winger   21     €90.00m         9      0   
9  10  Frenkie de Jong    Central Midfield   24     €90.00m         8      0   

   Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
0          0        5             2                

<span style="color:blue"><b>Task:</b></span> Add a new column with goals per game to the df!

In [29]:
df['goals_per_game']=df['Goals']/df['Matches']

In [30]:
df['goals_per_game']=np.where(df['Matches']==0,0,df['Goals']/df['Matches'])

You can also apply list comprehensions on series objects:

In [31]:
df['Last Name']= [name.split(' ')[-1] for name in df['Player']]
print(df['Last Name'])

0        Mbappé
1       Haaland
2          Kane
3      Grealish
4         Salah
         ...   
495      Davies
496    Hateboer
497        Raya
498       Kobel
499     Barrios
Name: Last Name, Length: 500, dtype: object


<span style="color:blue"><b>Task:</b></span> Convert the market value to a type float:

In [35]:
df['Market value']=[float(str(value).replace('€','').replace('m','').replace('\xa0','')) for value in df['Market value']]
print(df['Market value'])

0      160.0
1      150.0
2      120.0
3      100.0
4      100.0
       ...  
495     18.0
496     18.0
497     18.0
498     18.0
499     18.0
Name: Market value, Length: 500, dtype: float64


## Indexing and filtering <a id=filter>
[Back to Content Overview](#ov)

In [39]:
df.index=df['Player']
print(df)

                  #          Player            Position  Age  Market value  \
Player                                                                       
Kylian Mbappé     1   Kylian Mbappé      Centre-Forward   22         160.0   
Erling Haaland    2  Erling Haaland      Centre-Forward   21         150.0   
Harry Kane        3      Harry Kane      Centre-Forward   28         120.0   
Jack Grealish     4   Jack Grealish         Left Winger   26         100.0   
Mohamed Salah     5   Mohamed Salah        Right Winger   29         100.0   
...             ...             ...                 ...  ...           ...   
Tom Davies      496      Tom Davies    Central Midfield   23          18.0   
Hans Hateboer   497   Hans Hateboer          Right-Back   27          18.0   
David Raya      498      David Raya          Goalkeeper   26          18.0   
Gregor Kobel    499    Gregor Kobel          Goalkeeper   23          18.0   
Wilmar Barrios  500  Wilmar Barrios  Defensive Midfield   27    

<span style="color:blue"><b>Task:</b></span> Restore the old index.

In [38]:
df.index=range(len(df))
print(df)

       #          Player            Position  Age  Market value  Matches  \
0      1   Kylian Mbappé      Centre-Forward   22         160.0       11   
1      2  Erling Haaland      Centre-Forward   21         150.0        8   
2      3      Harry Kane      Centre-Forward   28         120.0       10   
3      4   Jack Grealish         Left Winger   26         100.0       10   
4      5   Mohamed Salah        Right Winger   29         100.0        9   
..   ...             ...                 ...  ...           ...      ...   
495  496      Tom Davies    Central Midfield   23          18.0        5   
496  497   Hans Hateboer          Right-Back   27          18.0        0   
497  498      David Raya          Goalkeeper   26          18.0        7   
498  499    Gregor Kobel          Goalkeeper   23          18.0       12   
499  500  Wilmar Barrios  Defensive Midfield   27          18.0       10   

     Goals  Own goals  Assists  Yellow cards  Yellow red cards  Red cards  \
0        4

In [42]:
# Query Columns with brackets and Column Name
#print(df['Last Name'])
# Query a element with  Column Name and vector index
print(df['Last Name'][3])

Grealish


C:\Users\myfix\AppData\Local\Temp\ipykernel_29196\2292259755.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df['Last Name'][3])


### loc
Use loc to get elements with their row and column names:

In [43]:
# Get values for Salah
df.loc['Mohamed Salah',:]

#                                5
Player               Mohamed Salah
Position              Right Winger
Age                             29
Market value                 100.0
Matches                          9
Goals                            9
Own goals                        0
Assists                          3
Yellow cards                     1
Yellow red cards                 0
Red cards                        0
Substitutions on                 0
Substitutions off                2
Scorer Points                   12
goals_per_game                 1.0
Last Name                    Salah
Name: Mohamed Salah, dtype: object

<span style="color:blue"><b>Task:</b></span> Get Salahs Age:

In [44]:
df.loc['Mohamed Salah','Age']

29

### iloc
Use iloc to get elements with their row and column indices:

In [45]:
# Get values for most valuable player
df.iloc[0,:]

#                                 1
Player                Kylian Mbappé
Position             Centre-Forward
Age                              22
Market value                  160.0
Matches                          11
Goals                             4
Own goals                         0
Assists                           5
Yellow cards                      2
Yellow red cards                  0
Red cards                         0
Substitutions on                  0
Substitutions off                 5
Scorer Points                     9
goals_per_game             0.363636
Last Name                    Mbappé
Name: Kylian Mbappé, dtype: object

<span style="color:blue"><b>Task:</b></span> Get the last column for the ten most valuable players:

In [47]:
df.iloc[:10,-2]

Player
Kylian Mbappé      0.363636
Erling Haaland     1.375000
Harry Kane         0.600000
Jack Grealish      0.200000
Mohamed Salah      1.000000
Romelu Lukaku      0.444444
Kevin De Bruyne    0.285714
Neymar             0.142857
Jadon Sancho       0.000000
Frenkie de Jong    0.000000
Name: goals_per_game, dtype: float64

### filter

You can filter the dataframe with conditions similar to the numpy vectors:

In [50]:
# Only keep players with had at least one game
df_filter=df[df['Matches']>0]
print(df_filter)

                  #          Player            Position  Age  Market value  \
Player                                                                       
Kylian Mbappé     1   Kylian Mbappé      Centre-Forward   22         160.0   
Erling Haaland    2  Erling Haaland      Centre-Forward   21         150.0   
Harry Kane        3      Harry Kane      Centre-Forward   28         120.0   
Jack Grealish     4   Jack Grealish         Left Winger   26         100.0   
Mohamed Salah     5   Mohamed Salah        Right Winger   29         100.0   
...             ...             ...                 ...  ...           ...   
Diego Rossi     495     Diego Rossi         Left Winger   23          18.0   
Tom Davies      496      Tom Davies    Central Midfield   23          18.0   
David Raya      498      David Raya          Goalkeeper   26          18.0   
Gregor Kobel    499    Gregor Kobel          Goalkeeper   23          18.0   
Wilmar Barrios  500  Wilmar Barrios  Defensive Midfield   27    

In [53]:
# Only keep players who are under 25 and have an market values over 50 mio:
df['Market value'] = [float(str(value).replace('€','').replace('m','')) for value in df['Market value']]
df_filter=df[(df['Age']<25) & (df['Market value']>50)] # use | for or
print(len(df_filter))

35


You can also use list comprehensions with booleans to takle more complicated conditions:

<span style="color:blue"><b>Task:</b></span> Only keep players with a middle name. (Name consists of more than 2 words.)

In [56]:
df[[True if player.count(' ')>1 else False for player in df['Player']]]
df_filter=df[[player.count(' ')>1 for player in df['Player']]]

Use ``df.drop_duplicates()`` to delete duplicates from your dataset:

In [59]:
print(df.drop_duplicates(subset='Position'))

                          #                  Player            Position  Age  \
Player                                                                         
Kylian Mbappé             1           Kylian Mbappé      Centre-Forward   22   
Jack Grealish             4           Jack Grealish         Left Winger   26   
Mohamed Salah             5           Mohamed Salah        Right Winger   29   
Kevin De Bruyne           7         Kevin De Bruyne  Attacking Midfield   30   
Frenkie de Jong          10         Frenkie de Jong    Central Midfield   24   
Joshua Kimmich           12          Joshua Kimmich  Defensive Midfield   26   
João Félix               18              João Félix      Second Striker   21   
Matthijs de Ligt         24        Matthijs de Ligt         Centre-Back   22   
Trent Alexander-Arnold   25  Trent Alexander-Arnold          Right-Back   23   
Alphonso Davies          29         Alphonso Davies           Left-Back   20   
Jan Oblak                41             

<span style="color:blue"><b>Task:</b></span> Only show the player with the highest market value for every age.

In [60]:
df.drop_duplicates(subset='Age')

#              Player            Position  Age  \
Player                                                                 
Kylian Mbappé         1       Kylian Mbappé      Centre-Forward   22   
Erling Haaland        2      Erling Haaland      Centre-Forward   21   
Harry Kane            3          Harry Kane      Centre-Forward   28   
Jack Grealish         4       Jack Grealish         Left Winger   26   
Mohamed Salah         5       Mohamed Salah        Right Winger   29   
Kevin De Bruyne       7     Kevin De Bruyne  Attacking Midfield   30   
Frenkie de Jong      10     Frenkie de Jong    Central Midfield   24   
Bruno Fernandes      11     Bruno Fernandes  Attacking Midfield   27   
Marcus Rashford      14     Marcus Rashford         Left Winger   23   
Pedri                17               Pedri    Central Midfield   18   
Lionel Messi         22        Lionel Messi        Right Winger   34   
Alphonso Davies      29     Alphonso Davies           Left-Back   20   
Rodri                32               Rodri  Defensive Midfield   25   
Robert Lewandowski   65  Robert Lewandowski      Centre-Forward   33   
Cristiano Ronaldo   112   Cristiano Ronaldo      Centre-Forward   36   
Nuno Mendes         119         Nuno Mendes           Left-Back   19   
Toni Kroos          153          Toni Kroos    Central Midfield   31   
Thomas Müller       241       Thomas Müller      Second Striker   32   
Youssoufa Moukoko   481   Youssoufa Moukoko      Centre-Forward   16   

                    Market value  Matches  Goals  Own goals  Assists  \
Player                                                                 
Kylian Mbappé              160.0       11      4          0        5   
Erling Haaland             150.0        8     11          0        4   
Harry Kane                 120.0       10      6          0        0   
Jack Grealish              100.0       10      2          0        2   
Mohamed Salah              100.0        9      9          0        3   
Kevin De Bruyne            100.0        7      2          0        0   
Frenkie de Jong             90.0        8      0          0        2   
Bruno Fernandes             90.0       11      5          0        3   
Marcus Rashford             85.0        0      0          0        0   
Pedri                       80.0        5      0          0        0   
Lionel Messi                80.0        5      1          0        0   
Alphonso Davies             70.0       10      0          0        3   
Rodri                       70.0        8      1          0        0   
Robert Lewandowski          60.0       10     13          0        1   
Cristiano Ronaldo           45.0        7      5          0        0   
Nuno Mendes                 40.0       10      0          1        1   
Toni Kroos                  40.0        2      0          0        0   
Thomas Müller               30.0       11      4          0        6   
Youssoufa Moukoko           18.0       10      3          0        1   

                    Yellow cards  Yellow red cards  Red cards  \
Player                                                          
Kylian Mbappé                  2                 0          0   
Erling Haaland                 1                 0          0   
Harry Kane                     2                 0          0   
Jack Grealish                  1                 0          0   
Mohamed Salah                  1                 0          0   
Kevin De Bruyne                1                 0          0   
Frenkie de Jong                0                 1          0   
Bruno Fernandes                2                 0          0   
Marcus Rashford                0                 0          0   
Pedri                          0                 0          0   
Lionel Messi                   1                 0          0   
Alphonso Davies                1                 0          0   
Rodri                          2                 0          0   
Robert Lewandowski   

<span style="color:blue"><b>Task:</b></span> Only show the player with the lowest market value for every age.

In [62]:
df.drop_duplicates(subset='Age',keep='last')

#              Player            Position  Age  \
Player                                                                 
Lionel Messi         22        Lionel Messi        Right Winger   34   
Cristiano Ronaldo   112   Cristiano Ronaldo      Centre-Forward   36   
Rayan Cherki        344        Rayan Cherki  Attacking Midfield   18   
Portu               457               Portu        Right Winger   29   
Julian Draxler      460      Julian Draxler         Left Winger   28   
Jordi Alba          462          Jordi Alba           Left-Back   32   
Sergio Canales      463      Sergio Canales  Attacking Midfield   30   
Ángel Di María      465      Ángel Di María        Right Winger   33   
Miralem Pjanic      466      Miralem Pjanic    Central Midfield   31   
Noni Madueke        476        Noni Madueke        Right Winger   19   
William Saliba      479      William Saliba         Centre-Back   20   
Youssoufa Moukoko   481   Youssoufa Moukoko      Centre-Forward   16   
Ryan Sessegnon      484      Ryan Sessegnon       Left Midfield   21   
Kyle Walker-Peters  489  Kyle Walker-Peters          Right-Back   24   
Riqui Puig          492          Riqui Puig    Central Midfield   22   
Éverton             493             Éverton         Left Winger   25   
David Raya          498          David Raya          Goalkeeper   26   
Gregor Kobel        499        Gregor Kobel          Goalkeeper   23   
Wilmar Barrios      500      Wilmar Barrios  Defensive Midfield   27   

                    Market value  Matches  Goals  Own goals  Assists  \
Player                                                                 
Lionel Messi                80.0        5      1          0        0   
Cristiano Ronaldo           45.0        7      5          0        0   
Rayan Cherki                23.0       10      4          0        2   
Portu                       20.0        9      0          0        0   
Julian Draxler              20.0        9      2          0        1   
Jordi Alba                  20.0        4      0          0        1   
Sergio Canales              20.0        8      1          0        2   
Ángel Di María              20.0        6      1          0        2   
Miralem Pjanic              20.0        5      0          0        3   
Noni Madueke                18.0       15      6          0        1   
William Saliba              18.0       11      0          0        0   
Youssoufa Moukoko           18.0       10      3          0        1   
Ryan Sessegnon              18.0        3      0          0        0   
Kyle Walker-Peters          18.0        6      1          0        1   
Riqui Puig                  18.0        4      0          0        0   
Éverton                     18.0       13      0          0        1   
David Raya                  18.0        7      0          0        0   
Gregor Kobel                18.0       12      0          0        0   
Wilmar Barrios              18.0       10      0          0        0   

                    Yellow cards  Yellow red cards  Red cards  \
Player                                                          
Lionel Messi                   1                 0          0   
Cristiano Ronaldo              2                 0          0   
Rayan Cherki                   1                 0          0   
Portu                          1                 0          0   
Julian Draxler                 1                 0          0   
Jordi Alba                     1                 0          0   
Sergio Canales                 1                 0          0   
Ángel Di María                 1                 0          0   
Miralem Pjanic                 1                 0          0   
Noni Madueke                   0                 0          0   
William Saliba                 2                 0          0   
Youssoufa Moukoko              1                 0          0   
Ryan Sessegnon                 0                 0          0   
Kyle Walker-Peters   

In [63]:
df.sort_values('Market value',ascending=True).drop_duplicates(subset='Age')

#               Player            Position  Age  \
Player                                                                   
Wilmar Barrios       500       Wilmar Barrios  Defensive Midfield   27   
Mohamed Simakan      472      Mohamed Simakan         Centre-Back   21   
Rayan Aït Nouri      473      Rayan Aït Nouri           Left-Back   20   
Amad Diallo          474          Amad Diallo        Right Winger   19   
Wendel               478               Wendel    Central Midfield   24   
Youssoufa Moukoko    481    Youssoufa Moukoko      Centre-Forward   16   
Gregor Kobel         499         Gregor Kobel          Goalkeeper   23   
Alexis Saelemaekers  486  Alexis Saelemaekers        Right Winger   22   
Éverton              493              Éverton         Left Winger   25   
David Raya           498           David Raya          Goalkeeper   26   
Danilo               452               Danilo          Right-Back   30   
Serge Aurier         454         Serge Aurier          Right-Back   28   
Emil Forsberg        456        Emil Forsberg         Left Winger   29   
Kieran Trippier      458      Kieran Trippier          Right-Back   31   
Jordi Alba           462           Jordi Alba           Left-Back   32   
Ángel Di María       465       Ángel Di María        Right Winger   33   
Rayan Cherki         344         Rayan Cherki  Attacking Midfield   18   
Cristiano Ronaldo    112    Cristiano Ronaldo      Centre-Forward   36   
Lionel Messi          22         Lionel Messi        Right Winger   34   

                     Market value  Matches  Goals  Own goals  Assists  \
Player                                                                  
Wilmar Barrios               18.0       10      0          0        0   
Mohamed Simakan              18.0        9      0          0        0   
Rayan Aït Nouri              18.0        3      0          0        1   
Amad Diallo                  18.0        0      0          0        0   
Wendel                       18.0       13      3          0        2   
Youssoufa Moukoko            18.0       10      3          0        1   
Gregor Kobel                 18.0       12      0          0        0   
Alexis Saelemaekers          18.0        9      0          0        2   
Éverton                      18.0       13      0          0        1   
David Raya                   18.0        7      0          0        0   
Danilo                       20.0        7      0          0        0   
Serge Aurier                 20.0        0      0          0        0   
Emil Forsberg                20.0       10      2          0        1   
Kieran Trippier              20.0        9      0          0        0   
Jordi Alba                   20.0        4      0          0        1   
Ángel Di María               20.0        6      1          0        2   
Rayan Cherki                 23.0       10      4          0        2   
Cristiano Ronaldo            45.0        7      5          0        0   
Lionel Messi                 80.0        5      1          0        0   

                     Yellow cards  Yellow red cards  Red cards  \
Player                                                           
Wilmar Barrios                  0                 0          0   
Mohamed Simakan                 0                 0          0   
Rayan Aït Nouri                 0                 0          0   
Amad Diallo                     0                 0          0   
Wendel                          2                 0          0   
Youssoufa Moukoko               1                 0          0   
Gregor Kobel                    0                 0          0   
Alexis Saelemaekers             1                 0          0   
Éverton                         1                 0          0   
David Raya                      0                 0          0   
Danilo                          1                 0          0   
Serge Aurier                    0                 0          0   
Emil Forsb

Use ``df.sample()`` to get a random sample form your dataset:

In [69]:
# Choose 5 players randomly from the datasset
print(df.sample(5).iloc[:,:6])


                   #           Player          Position  Age  Market value  \
Player                                                                       
Alisson           62          Alisson        Goalkeeper   29          60.0   
Matthias Ginter  268  Matthias Ginter       Centre-Back   27          27.0   
Weston McKennie  300  Weston McKennie  Central Midfield   23          25.0   
Jérémy Doku      270      Jérémy Doku      Right Winger   19          26.0   
Victor Osimhen    79   Victor Osimhen    Centre-Forward   22          50.0   

                 Matches  
Player                    
Alisson                9  
Matthias Ginter        7  
Weston McKennie        7  
Jérémy Doku            4  
Victor Osimhen         8  


<span style="color:blue"><b>Task:</b></span> Choose 10% of the df.

In [71]:
df.sample(int(len(df)*0.1))
df.sample(frac=0.1)

#                 Player            Position  Age  \
Player                                                                       
Sadio Mané              15             Sadio Mané         Left Winger   29   
Ferland Mendy           86          Ferland Mendy           Left-Back   26   
Dodô                   408                   Dodô          Right-Back   22   
Gabriel Martinelli     349     Gabriel Martinelli         Left Winger   20   
Harry Winks            437            Harry Winks  Defensive Midfield   25   
Alex Iwobi             375             Alex Iwobi         Left Winger   25   
Noni Madueke           476           Noni Madueke        Right Winger   19   
Diogo Jota              99             Diogo Jota         Left Winger   24   
Enock Mwepu            401            Enock Mwepu    Central Midfield   23   
Tariq Lamptey          475          Tariq Lamptey          Right-Back   21   
Mikel Merino           133           Mikel Merino    Central Midfield   25   
Riqui Puig             492             Riqui Puig    Central Midfield   22   
James Maddison          84         James Maddison  Attacking Midfield   24   
Victor Osimhen          79         Victor Osimhen      Centre-Forward   22   
Ricardo Pereira        227        Ricardo Pereira          Right-Back   28   
Kalidou Koulibaly       94      Kalidou Koulibaly         Centre-Back   30   
Duván Zapata           196           Duván Zapata      Centre-Forward   30   
John Stones            232            John Stones         Centre-Back   27   
Fred                   378                   Fred    Central Midfield   28   
Denis Zakaria          263          Denis Zakaria  Defensive Midfield   24   
Arthur                 129                 Arthur    Central Midfield   25   
Jonathan Ikoné         302         Jonathan Ikoné      Second Striker   23   
Phil Foden              19             Phil Foden    Central Midfield   21   
David Neres            353            David Neres        Right Winger   24   
Diego Rossi            495            Diego Rossi         Left Winger   23   
Julian Weigl           446           Julian Weigl  Defensive Midfield   26   
Richarlison             67            Richarlison      Centre-Forward   24   
Patson Daka            359            Patson Daka      Centre-Forward   23   
Tetê                   413                   Tetê        Right Winger   21   
Nabil Fekir            317            Nabil Fekir  Attacking Midfield   28   
Houssem Aouar          167          Houssem Aouar    Central Midfield   23   
Rayan Cherki           344           Rayan Cherki  Attacking Midfield   18   
Danny Ings             384             Danny Ings      Centre-Forward   29   
Marcel Sabitzer        208        Marcel Sabitzer    Central Midfield   27   
Ciro Immobile          158          Ciro Immobile      Centre-Forward   31   
Aaron Ramsdale         405         Aaron Ramsdale          Goalkeeper   23   
Unai Simón             432             Unai Simón          Goalkeeper   24   
Tomas Soucek           115           Tomas Soucek  Defensive Midfield   26   
Jeff Reine-Adélaïde    424    Jeff Reine-Adélaïde  Attacking Midfield   23   
Christopher Nkunku      95     Christopher Nkunku  Attacking Midfield   23   
Ivan Toney             203             Ivan Toney      Centre-Forward   25   
Joachim Andersen       373       Joachim Andersen         Centre-Back   25   
David Raya             498             David Raya          Goalkeeper   26   
Heung-min Son           16          Heung-min Son         Left Winger   29   
Thibaut Courtois        61       Thibaut Courtois          Goalkeeper   29   
Marc-André ter Stegen   63  Marc-André ter Stegen          Goalkeeper   29   
Kalvin Phillips        131        Kalvin Phillips  Defensive Midfield   25   
Marco Verratti          75         Marco Verratti    Central Midfield   28   
Mike Maignan           321           Mike Maignan          Goalkeeper   26   
Amadou Haidara         338         Amadou Haida

### Group by



In [75]:
print(df.select_dtypes(include='number').groupby(df['Position']).mean())

                             #        Age  Market value   Matches     Goals  \
Position                                                                      
Attacking Midfield  241.731707  24.365854     36.804878  7.926829  1.853659   
Central Midfield    231.337838  25.054054     36.702703  7.351351  0.864865   
Centre-Back         250.735632  24.839080     33.137931  7.597701  0.252874   
Centre-Forward      235.507463  25.716418     38.194030  7.865672  3.567164   
Defensive Midfield  258.317073  25.048780     34.292683  7.731707  0.609756   
Goalkeeper          300.681818  26.227273     32.818182  7.909091  0.000000   
Left Midfield       317.000000  23.142857     29.285714  7.285714  1.571429   
Left Winger         230.404255  24.319149     40.234043  8.170213  1.680851   
Left-Back           242.750000  25.333333     33.875000  6.333333  0.458333   
Right Midfield      293.333333  25.333333     25.666667  4.666667  0.000000   
Right Winger        253.434783  24.391304     34.043

<span style="color:blue"><b>Task:</b></span> Show the mean market value for each position for each age.

In [76]:
df_agg=df[['Market value','Position','Age']].groupby(['Position','Age']).mean()
df_agg

Market value
Position           Age              
Attacking Midfield 18      45.000000
                   20      20.000000
                   21      22.666667
                   22      51.750000
                   23      34.250000
...                              ...
Second Striker     22      20.000000
                   23      25.000000
                   27      40.000000
                   30      41.500000
                   32      30.000000

[138 rows x 1 columns]

<span style="color:blue"><b>Task:</b></span> Add a new column to the df with the mean market value respective to the position (Use a list comprehension)

In [80]:
# Create a series with maps the postion to its mean market value
postion_mean=df[['Market value','Position']].groupby('Position').mean()
print(postion_mean)
# Create a new column and fill it with the the position means
df['Position mean']=[postion_mean.loc[position,'Market value'] for position in df['Position']]

print(df['Position mean'])

                    Market value
Position                        
Attacking Midfield     36.804878
Central Midfield       36.702703
Centre-Back            33.137931
Centre-Forward         38.194030
Defensive Midfield     34.292683
Goalkeeper             32.818182
Left Midfield          29.285714
Left Winger            40.234043
Left-Back              33.875000
Right Midfield         25.666667
Right Winger           34.043478
Right-Back             28.515152
Second Striker         39.750000
Player
Kylian Mbappé     38.194030
Erling Haaland    38.194030
Harry Kane        38.194030
Jack Grealish     40.234043
Mohamed Salah     34.043478
                    ...    
Tom Davies        36.702703
Hans Hateboer     28.515152
David Raya        32.818182
Gregor Kobel      32.818182
Wilmar Barrios    34.292683
Name: Position mean, Length: 500, dtype: float64


<span style="color:blue"><b>Task:</b></span> Apply Position Fixed Effects

In [82]:
df['MV_FE']=df['Market value']-df['Position mean']

In [83]:
df['MV_FE']

Player
Kylian Mbappé     121.805970
Erling Haaland    111.805970
Harry Kane         81.805970
Jack Grealish      59.765957
Mohamed Salah      65.956522
                     ...    
Tom Davies        -18.702703
Hans Hateboer     -10.515152
David Raya        -14.818182
Gregor Kobel      -14.818182
Wilmar Barrios    -16.292683
Name: MV_FE, Length: 500, dtype: float64